files:
  sensitivity: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/ectuner/sensitivities/sensitivity_TL63_415_{year1}-{year2}.yaml
  base: GM_EC26-HIST_{exp}_EC-Earth4_r1i1p1f1_{year1}_{year2}.yml
  params: tuning_{exp}.yml
  ecmean: /home/ecme3038/hpcperm/ecearth/ecearth4/ECtuner/ectuner/ecmean/gm_TL63_v2/
  exps: /home/ecme3038/hpcperm/ecearth/ecearth4/ECtuner/ectuner/perturb_exps/exps_TL63_v2/
  exp_temp: "p???" # Template for tags (es. 00, 01, 02)

ecmean:
  ecmean_config: config_ecmean.yml

args:
  ref_tag: "p000"
  # Default years for sensitivities
  year1: 1991
  year2: 2000
  

reference_parameters: # Default OIFS parameter values (used for penalty)
  RPRCON: 0.0014
  ENTRORG: 0.00175
  DETRPEN: 7.5e-05
  ENTRDD: 0.0003
  RMFDEPS: 0.3
  RVICE: 0.13
  RLCRITSNOW: 2.0e-05 
  RSNOWLIN2: 0.03
  RCLDIFF: 0.6e-05
  RCLDIFF_CONVI: 10.0
  RDEPLIQREFRATE: 0.5 
  RDEPLIQREFDEPTH: 500.0 
  RCL_OVERLAPLIQICE: 0.65
  RCL_INHOMOGAUT: 1.5
  RCL_INHOMOGACC: 3
  RMINICE: 60
