files:
  #1D
  reference: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/data/ecmean/reference/gm_reference_EC26-PDAY.yml  # Target observations (Obs)
  #sensitivity: sensitivities/sensitivity_TL63_415_1991-2000.yaml  # sensitivity file template
  sensitivity: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/data/sensitivities/sensitivity_TL63_415_1991-2000.yaml  # sensitivity file template
  slope_file: utils/slopes.yaml # file with slopes for temperature correction
  ecmean: "/ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/mari/ectuner/ecmean/gm_lres/" # Directory for 'base' ECmean files
  ecmean_config: /percorso/al/config_ecmean.yml
  base: GM_EC26-PDAY_{exp}_EC-Earth4_r1i1p1f1_{year1}_{year2}.yml  # ECmean output pattern for the experiment to be tuned
  
  #2D
  ref_2d_dir: "/ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/data/ecmean/reference/climatology/EC26-PDAY/r180x90/"
  sensitivity_nc: "/ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/data/sensitivities/2D/sensitivity_TL63_415_1991-2000_2D.nc"
  raw_dir: "/ec/res4/scratch/ecme3038/ece4/" 
  base_2d_dir: "/ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/mari/ectuner/ecmean/maps_lres/"
  
  #Common
  params: tuning_{exp}.yml  # template for your tuining file
  exps: "/ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/mari/ectuner/perturb_exps/exps_lres/" # Directory for 'params' tuning files
  output_dir: "/ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/mari/results/tuned_2d_LR/refactor/2d/CLI/" # Directory for tuning output

args:
  year1: 2000
  year2: 2017
  penalty: 0  # Penalty for deviation from reference parameter values
  inc: 0.3  # Maximum acceptable parameter change
  method: 'dual_annealing' # Optimization method (dual_annealing (recommended), differential_evolution, shgo (not recommended))
  
  #1D specific args
  model_imbalance:  # Model imbalance to be corrected: - (netTOA-netSFC) + (oce_imbalance), -0.74 for low res
  deltaT:  # Time step for the reference correction 

#2d tuning options
spatial_tuning:
  target_grid: "r180x90"
  alpha: 0 # Hybrid weight (0: spatial, 1: global)
  metric: "l1" # Metric for spatial tuning (e.g., l1, l2, rmse)
  area_weighting: True
  #r2_threshold: 0.0 # Ignore pixels where the linear relationship between parameter and response is weak

# Parameters to keep fixed during tuning (example)
frozen_parameters:
  #RPRCON: default
  #ENTRORG: selected value

reference_parameters: # Default OIFS parameter values (used for penalty)
  RPRCON: 0.14E-02     # coefficients for determining conversion from cloud water to rain
  ENTRORG: 0.175E-02   # entrainment rate (positive buoyant convection)
  DETRPEN: 0.75E-04    # detrainment rate for penetrative convection
  ENTRDD: 0.3E-03      # entrainment rate for cumulus downdrafts
  RMFDEPS: 0.3         # fractional massflux for downdrafts at lfs
  RVICE: 0.13          # fixed ice fallspeed
  RLCRITSNOW: 2E-05  # critical autoconversion threshold
  RSNOWLIN2: 0.3E-01   # Constant governing of the temperature dependence of the autoconversion
                      # of ice crystals to snow in large-scale precipitation
  RCLDIFF: 0.6e-05   #correct value from OpenIFS namelist : 0.6e-05  # diffusion-coefficient for evaporation by turbulent mixing
  RCLDIFF_CONVI: 10.0   # enhancement factor of rcldiff for convection
  RDEPLIQREFRATE: 0.5 # (50% deposition efficiency in top layer)
  RDEPLIQREFDEPTH: 500.0 #m (recovery depth scale)
  RCL_OVERLAPLIQICE: 0.65 #overlap assumption for liquid and ice for deposition
  RCL_INHOMOGAUT: 1.5
  RCL_INHOMOGACC: 3
  RMINICE: 60          # minimum ice crystal radius for sedimentation (microns)


parameter_group: # Parameter grouping for SE output
  namcumf: 
    - RPRCON
    - ENTRORG
    - DETRPEN
    - ENTRDD
    - RMFDEPS
  namcldp:
    - RVICE
    - RLCRITSNOW
    - RSNOWLIN2
    - RCLDIFF
    - RCLDIFF_CONVI
    - RDEPLIQREFRATE
    - RDEPLIQREFDEPTH
    - RCL_OVERLAPLIQICE
    - RCL_INHOMOGAUT
    - RCL_INHOMOGACC
  naerad:
    - RMINICE

weights:  # Weights for different target variables
  net_toa: 1.0
  rsnt: 0.0
  rlnt: 0.0
  swcf: 0.0
  lwcf: 0.0
  rsns: 0.
  rlns: 0.
  hfss: 0.
  hfls: 0.
  net_sfc: 0.
  toamsfc: 0.

weights_region:  # Weights for different regions
  Global: 1.0
  Tropical: 0.
  North Midlat: 0
  South Midlat: 0.
  NH: 0.
  SH: 0.
  Equatorial: 0.
  North Pole: 0.
  South Pole: 0.

weights_season:  # Weights for different seasons
  ALL: 1.0
  DJF: 0.
  JJA: 0.
