files:
  # INPUT DATA
  reference: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/ectuner/ecmean/reference/gm_reference_EC26-PDAY.yml  # Reference file based on obs (our target)
  sensitivity: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/ectuner/sensitivities/sensitivity_TL255_415_1991-2000_v2.yaml  # sensitivity file template
  slope_file: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/ectuner/utils/slopes.yaml # file with slopes for temperature correction
  # TEMPLATES
  base: global_mean_ftv9_EC-Earth4_r1i1p1f1_{year1}_{year2}.yml  # template for ecmean output filenames, name of the file to tune
  params: tuning_{exp}.yml  # template for parameter files
  output_template: prova_2_tuned_{exp}_{year1}_{year2}.yml  # template for the output file name
  #DIRECTORIES
  ecmean: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/mari/ectuner/ecmean/gm_sres  # directory for ecmean output files
  exps: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/mari/ectuner/perturb_exps/exps_sres  # directory for parameter files for each experiment
  output_dir: /ec/res4/hpcperm/ecme3038/ecearth/ecearth4/ECtuner/mari/results/tuned/ # Directory for tuning output

args:
  # Default years for sensitivities
  year1: 1991
  year2: 2000
  penalty: 10  # Penalty for deviation from reference parameter values
  inc: 0.6 # Maximum acceptable parameter change
  method: 'dual_annealing' # Optimization method (dual_annealing (recommended), differential_evolution, shgo (not recommended))
  #model_imbalance: -0.6 # Model imbalance to be corrected: - (netTOA-netSFC) + (oce_imbalance)
  deltaT: 0.6 # Temperature step for the reference correction

frozen_parameters:
  - RCL_OVERLAPLIQICE

reference_parameters: # Default OIFS parameter values (used for penalty)
  RPRCON: 0.14E-02
  ENTRORG: 0.175E-02     
  DETRPEN: 0.75E-04    
  ENTRDD: 0.3E-03      
  RMFDEPS: 0.3         
  RVICE: 0.13          
  RLCRITSNOW: 2.0E-05  
  RSNOWLIN2: 0.3E-01   
  RCLDIFF: 0.3E-05     
  RCLDIFF_CONVI: 10.0   
  RDEPLIQREFRATE: 0.5 
  RDEPLIQREFDEPTH: 500.0 
  RCL_OVERLAPLIQICE: 0.65
  RCL_INHOMOGAUT: 1.5
  RCL_INHOMOGACC: 3
  RMINICE: 60  


parameter_group: # Parameter grouping for SE output
  namcumf: 
    - RPRCON
    - ENTRORG
    - DETRPEN
    - ENTRDD
    - RMFDEPS
  namcldp:
    - RVICE
    - RLCRITSNOW
    - RSNOWLIN2
    - RCLDIFF
    - RCLDIFF_CONVI
    - RDEPLIQREFRATE
    - RDEPLIQREFDEPTH
    - RCL_OVERLAPLIQICE
    - RCL_INHOMOGAUT
    - RCL_INHOMOGACC
  naerad:
    - RMINICE
  
weights_season:  # Weights for different seasons
  ALL: 1.0
  DJF: 0.
  JJA: 0.

weights_region:  # Weights for different regions
  Global: 1.0
  Tropical: 0.
  North Midlat: 0.
  South Midlat: 0.
  NH: 0.
  SH: 0.
  Equatorial: 0.
  North Pole: 0.
  South Pole: 0.

weights:  # Weights for different target variables
  net_toa: 3.0
  rsnt: 2.5
  rlnt: 2.5
  swcf: 0.
  lwcf: 0.
  rsns: 0.
  rlns: 0.
  hfss: 0.
  hfls: 0.
  net_sfc: 0.
  toamsfc: 0.
