"""
Diagnostic Visualization Module.

Reads structured diagnostic YAML files generated by ECtuner and creates
visualizations for parameter changes, score evolution, bias reduction,
and Pareto front tradeoffs. Functions here can also validate the emulator's
predictions against actual realized model outputs.
"""
import os
import glob
import yaml
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import cartopy.crs as ccrs
import xarray as xr
from pathlib import Path
from typing import Dict, Any, List

# Try importing the regridder for validation plots from scratch
try:
    from .utils import regrid_to_regular_smm_safe, compute_derived_flux
except ImportError:
    regrid_to_regular_smm_safe = None
    compute_derived_flux = None

def _handle_show_or_save(output_path=None):
    """
    Internal helper to handle plot saving or showing cleanly.
    
    Args:
        output_path: If provided, saves the plot to this destination. 
            Otherwise, displays it interactively.
    """
    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        plt.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"Plot saved successfully to: {output_path}")
    else:
        plt.show()
    plt.close()

def load_diagnostic_yamls(folder_path: str) -> Dict[str, Any]:
    """
    Scans a folder for ECtuner diagnostic files and loads them.

    Args:
        folder_path: Path to the directory containing diagnostics YAMLs.

    Returns:
        A dictionary mapping experiment tags to their parsed diagnostic data.
        
    Raises:
        FileNotFoundError: If the specified folder does not exist.
    """
    folder = Path(folder_path)
    if not folder.exists():
        raise FileNotFoundError(f"Folder not found: {folder_path}")

    diag_data = {}
    files = sorted(folder.glob("diagnostics_*.yaml"))

    for filepath in files:
        tag = filepath.stem.replace("diagnostics_", "")
        with open(filepath, 'r') as f:
            diag_data[tag] = yaml.safe_load(f)
            
    print(f"Loaded {len(diag_data)} diagnostic files from {folder_path}")
    return diag_data


def build_metrics_dataframe(diag_data: Dict[str, Any]) -> pd.DataFrame:
    """
    Converts the nested YAML dictionary into a Pandas DataFrame optimized 
    for Pareto front and Tradeoff plotting.

    Args:
        diag_data: Data loaded via `load_diagnostic_yamls`.

    Returns:
        A DataFrame containing sorted metrics for all experiments, structured 
        to isolate Spatial vs Global costs.
    """
    records = []
    
    for exp_tag, data in diag_data.items():
        metrics = data.get('metrics', {})
        record = {
            'Experiment': exp_tag,
            'Alpha': metrics.get('alpha', np.nan),
            'Metric': metrics.get('metric_name', 'l2'),
            'Raw_Spatial_Cost': metrics.get('total_spatial_cost', np.nan),
            'Raw_Global_Cost': metrics.get('total_global_cost', np.nan),
        }
        
        # Determine Physical Units based on metric type
        if record['Metric'] == 'l2':
            record['Metric_Type'] = 'L2 (Quadratic)'
            record['Phys_Spatial_Total'] = record['Raw_Spatial_Cost']
            record['Phys_Global_Total'] = record['Raw_Global_Cost']
        else:
            record['Metric_Type'] = 'L1 (Linear)'
            record['Phys_Spatial_Total'] = record['Raw_Spatial_Cost']
            record['Phys_Global_Total'] = record['Raw_Global_Cost']
            
        # Extract Variable-Specific Biases from the 'biases' block if needed
        # Assuming the structure is: biases -> targets -> list of dicts
        targets = data.get('biases', {}).get('targets', [])
        for t in targets:
            var = t['variable']
            if t['region'] == 'Global':
                record[f'{var}_AbsBias'] = abs(t['bias_final'])

        var_metrics = data.get('var_metrics', {})
        for var_name, stats in var_metrics.items():
            record[f'{var_name}_Spatial_Cost'] = stats.get('spatial_cost', np.nan)
                
        records.append(record)
        
    df = pd.DataFrame(records)
    if not df.empty:
        df.set_index('Experiment', inplace=True)
        df.sort_values(by='Alpha', inplace=True)
        
    return df

# ==============================================================================
# PARAMETER VISUALIZATIONS
# ==============================================================================

def plot_parameter_scatter(diag_data: Dict[str, Any], output_path: str = None) -> None:
    """
    Creates a scatter plot with parameters on the x-axis and their relative change.

    Visualizes how much each parameter drifted from its default reference value.
    A value of 0.0 means no change from the reference.

    Args:
        diag_data: Dictionary containing loaded diagnostic data.
        output_path: Optional file path to save the plot.
    """
    if not diag_data:
        print("No data to plot")
        return

    params_set = set()
    for data in diag_data.values():
        for p in data['parameters']:
            params_set.add(p['name'])
    all_params = sorted(list(params_set))

    fig, ax = plt.subplots(figsize=(max(12, len(all_params) * 0.8), 8))
    
    exp_names = list(diag_data.keys())
    colors = plt.cm.tab10(np.linspace(0, 1, len(exp_names)))
    
    for exp_idx, exp_name in enumerate(exp_names):
        x_positions = []
        y_values = []
        
        for param_idx, param_name in enumerate(all_params):
            param_data = next((p for p in diag_data[exp_name]['parameters'] if p['name'] == param_name), None)
            
            if param_data and float(param_data['ref_value']) != 0:
                x_positions.append(param_idx)
                # Modifica qui: Calcoliamo la variazione relativa (Relative Change) invece del valore assoluto
                rel_change = (float(param_data['new_value']) - float(param_data['ref_value'])) / float(param_data['ref_value'])
                y_values.append(rel_change)
        
        ax.scatter(x_positions, y_values, s=100, alpha=0.7, 
                   color=colors[exp_idx], label=exp_name, zorder=3)
    
    # Modifica qui: La linea di base ora è a y=0
    ax.axhline(y=0, color='black', linestyle='--', alpha=0.5, linewidth=1)
    
    ax.set_xticks(range(len(all_params)))
    ax.set_xticklabels(all_params, rotation=45, ha='right')
    # Modifica qui: Aggiornata la label dell'asse Y
    ax.set_ylabel('Relative change (w.r.t default)', fontsize=12)
    ax.set_xlabel('Parameters', fontsize=12)
    
    ax.legend(bbox_to_anchor=(1.02, 1), loc='upper left')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    _handle_show_or_save(output_path)

def plot_parameter_heatmap(diag_data: Dict[str, Any], output_path: str = None) -> None:
    """
    Creates a heatmap showing the normalized relative change of parameters.

    Provides a quick visual indication of which parameters were pushed 
    towards their upper or lower boundaries during tuning.

    Args:
        diag_data: Dictionary containing loaded diagnostic data.
        output_path: Optional file path to save the plot.
    """
    if not diag_data:
        return

    data_matrix = {}
    for exp_tag, data in diag_data.items():
        data_matrix[exp_tag] = {}
        for p in data['parameters']:
            if float(p['ref_value']) != 0:
                rel_change = (float(p['new_value']) - float(p['ref_value'])) / float(p['ref_value'])
                data_matrix[exp_tag][p['name']] = rel_change
    df = pd.DataFrame(data_matrix).T

    fig, ax = plt.subplots(figsize=(max(12, len(df.columns) * 0.8), max(4, len(df) * 0.6)))
    
    im = ax.imshow(df.values, aspect='auto', cmap='RdBu_r', vmin=-0.5, vmax=0.5)
    
    ax.set_xticks(np.arange(len(df.columns)))
    ax.set_xticklabels(df.columns, rotation=45, ha='right')
    ax.set_yticks(np.arange(len(df.index)))
    ax.set_yticklabels(df.index)

    plt.colorbar(im, ax=ax, label='Relative change')

    for i in range(len(df.index)):
        for j in range(len(df.columns)):
            val = df.iloc[i, j]
            if not np.isnan(val):
                text_color = "white" if abs(val) > 0.25 else "black"
                ax.text(j, i, f'{val:.2e}', ha="center", va="center", color=text_color, fontsize=8)

    plt.tight_layout()
    _handle_show_or_save(output_path)

# ==============================================================================
# SPATIAL DIAGNOSTICS & PARETO FRONTS
# ==============================================================================

def compute_diagnostic_metrics(ds: xr.Dataset, var: str):
    """
    Computes zonal metrics and plot limits for a given variable from the diagnostic NetCDF.
    
    Args:
        ds: The diagnostic NetCDF dataset containing initial and final bias maps.
        var: The name of the atmospheric variable.
        
    Returns:
        A tuple containing the initial bias, final bias, improvement map, 
        min/max limits for plotting, and zonal mean profiles.
    """
    b_init = ds[f'{var}_bias_init']
    b_final = ds[f'{var}_bias_final']
    improv = ds[f'{var}_improvement']

    vmax = float(max(abs(b_init).max().item(), abs(b_final).max().item()))
    vmin = -vmax
    
    zonal_init = b_init.mean(dim='lon')
    zonal_final = b_final.mean(dim='lon')
    
    return b_init, b_final, improv, vmin, vmax, zonal_init, zonal_final

def plot_tuning_results_maps(diag_file: str, output_dir: str, run_tag: str) -> None:
    """
    Generates 2D maps comparing Initial Bias vs Final Predicted Bias.

    Reads the diagnostic NetCDF map produced by ECtuner's 2D engine and 
    plots a four-panel figure: Initial Bias, Final Bias, Absolute Improvement,
    and the Zonal Bias profile.

    Args:
        diag_file: Path to the diagnostic NetCDF file.
        output_dir: Directory to save the output plots.
        run_tag: Identifier for the current experiment run.
    """
    ds = xr.open_dataset(diag_file)
    variables = [v.replace('_bias_init', '') for v in ds.data_vars if '_bias_init' in v]
    
    for var in variables:

        b_init, b_final, improv, vmin, vmax, zonal_init, zonal_final = compute_diagnostic_metrics(ds, var)

        fig = plt.figure(figsize=(24, 5))
        gs = fig.add_gridspec(1, 4, width_ratios=[1, 1, 1, 0.6])

        ax0 = fig.add_subplot(gs[0], projection=ccrs.PlateCarree())
        ax1 = fig.add_subplot(gs[1], projection=ccrs.PlateCarree())
        ax2 = fig.add_subplot(gs[2], projection=ccrs.PlateCarree())
        ax_zonal = fig.add_subplot(gs[3])
        
        im0 = b_init.plot(ax=ax0, transform=ccrs.PlateCarree(), cmap='RdBu_r', vmin=vmin, vmax=vmax, add_colorbar=False)
        ax0.set_title(f'{var} - Initial Bias')
        
        im1 = b_final.plot(ax=ax1, transform=ccrs.PlateCarree(), cmap='RdBu_r', vmin=vmin, vmax=vmax, add_colorbar=False)
        ax1.set_title(f'{var} - Final Bias (Predicted)')
        
        im2 = improv.plot(ax=ax2, transform=ccrs.PlateCarree(), cmap='PiYG', add_colorbar=False)
        ax2.set_title(f'{var} - Absolute Improvement')
        
        for ax in [ax0, ax1, ax2]:
            ax.coastlines()
            
        fig.colorbar(im1, ax=[ax0, ax1], location='bottom', label='Bias Units', fraction=0.05, pad=0.08)
        fig.colorbar(im2, ax=[ax2], location='bottom', label='Improvement', fraction=0.05, pad=0.08)

        ax_zonal.plot(zonal_init, ds.lat, label='Init (Red)', color='red', linestyle='--', lw=1.5)
        ax_zonal.plot(zonal_final, ds.lat, label='Final (Blue)', color='blue', lw=2)
        ax_zonal.axvline(0, color='black', lw=0.8, alpha=0.5)
        ax_zonal.set_title(f'{var} Zonal Bias')
        ax_zonal.legend(fontsize='small', loc='upper right')
        ax_zonal.grid(True, alpha=0.3)
        
        plot_name = f"comparison_2d_{var}_{run_tag}.png"
        os.makedirs(output_dir, exist_ok=True)
        plt.savefig(os.path.join(output_dir, plot_name), bbox_inches='tight', dpi=150)
        plt.close()

# ==============================================================================
def plot_tradeoff_comparison(df: pd.DataFrame, group_by: str = 'Metric_Type', output_path: str = None) -> None:
    """
    Plots the global Pareto front mapping total spatial error vs global bias.

    Allows dynamic grouping to visualize the tradeoffs encountered by the optimizer
    under different spatial weighting alphas.

    Args:
        df: DataFrame built from diagnostic data.
        group_by: Column name to group markers by.
        output_path: Optional file path to save the plot.
    """
    plt.figure(figsize=(9, 6.5))
    
    markers = ['o', 's', '^', 'D', 'v', 'P']
    last_sc = None
    legend_elements = []

    if group_by not in df.columns:
        df[group_by] = 'All Data'

    metrics_present = df['Metric'].unique() if 'Metric' in df.columns else []
    title_suffix = "(RMSE/MAE & Abs Bias)" if len(metrics_present) > 1 else ("(RMSE & Abs Bias)" if 'l2' in metrics_present else "(MAE & Abs Bias)")

    for i, group_name in enumerate(df[group_by].unique()):
        subset = df[df[group_by] == group_name].dropna(subset=['Phys_Spatial_Total', 'Phys_Global_Total']).sort_values('Alpha')
        if subset.empty: continue
        
        mkr = markers[i % len(markers)]
        last_sc = plt.scatter(subset['Phys_Spatial_Total'], subset['Phys_Global_Total'], 
                              c=subset['Alpha'], cmap='viridis', marker=mkr, s=140, edgecolors='black', zorder=3, vmin=0, vmax=1)
        plt.plot(subset['Phys_Spatial_Total'], subset['Phys_Global_Total'], linestyle='--', alpha=0.4, zorder=2)
        
        for _, row in subset.iterrows():
            plt.annotate(fr'$\alpha$={row["Alpha"]:.2f}', (row['Phys_Spatial_Total'], row['Phys_Global_Total']),
                         xytext=(5, 5), textcoords='offset points', fontsize=8, alpha=0.7)

        legend_elements.append(
            Line2D([0], [0], marker=mkr, color='w', label=str(group_name), 
                   markerfacecolor='gray', markersize=10, markeredgecolor='black')
        )
    
    legend_title = group_by.replace('_', ' ')
    plt.legend(handles=legend_elements, loc='upper right', title=legend_title)
    plt.title(f"Pareto Front: Total Spatial Error vs Total Global Bias\nUnits: {title_suffix}", fontsize=12, fontweight='bold')
    plt.xlabel("Total Spatial Error (Physical Units)", fontsize=11)
    plt.ylabel("Total Global Bias (Physical Units)", fontsize=11)
    
    if last_sc: plt.colorbar(last_sc).set_label(r'Alpha Value ($\alpha$)', fontsize=11)
    
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.tight_layout()
    _handle_show_or_save(output_path)

def plot_variable_pareto(df: pd.DataFrame, var: str, group_by: str = 'Metric_Type', output_path: str = None) -> None:
    """
    Pareto Front specific to a single atmospheric variable.

    Args:
        df: DataFrame built from diagnostic data.
        var: The specific atmospheric variable to plot (e.g., 'net_toa').
        group_by: Column name to group markers by.
        output_path: Optional file path to save the plot.
    """
    plt.figure(figsize=(9, 6.5))
    
    col_bias = f'{var}_AbsBias'
    col_spat = f'{var}_Spatial_Cost'

    if col_bias not in df.columns:
        print(f"Variable {var} not found in DataFrame for Pareto plot.")
        return
    
    markers = ['o', 's', '^', 'D', 'v', 'P']
    last_sc = None
    legend_elements = []

    if group_by not in df.columns:
        df[group_by] = 'All Data'

    for i, group_name in enumerate(df[group_by].unique()):
        subset = df[df[group_by] == group_name].dropna(subset=[col_spat, col_bias]).sort_values('Alpha')
        if subset.empty: continue
        
        mkr = markers[i % len(markers)]
        last_sc = plt.scatter(subset[col_spat], subset[col_bias], 
                              c=subset['Alpha'], cmap='viridis', marker=mkr, s=140, edgecolors='black', zorder=3, vmin=0, vmax=1)
        plt.plot(subset[col_spat], subset[col_bias], linestyle='--', alpha=0.4, zorder=2)
        
        for _, row in subset.iterrows():
            plt.annotate(fr'$\alpha$={row["Alpha"]:.2f}', (row[col_spat], row[col_bias]),
                         xytext=(5, 5), textcoords='offset points', fontsize=8, alpha=0.7)

        legend_elements.append(
            Line2D([0], [0], marker=mkr, color='w', label=str(group_name), 
                   markerfacecolor='gray', markersize=10, markeredgecolor='black')
        )

    legend_title = group_by.replace('_', ' ')
    plt.legend(handles=legend_elements, loc='upper right', title=legend_title)
        
    plt.title(f"Pareto Front: Spatial Error vs Global Bias ({var.upper()})", fontsize=12, fontweight='bold')
    plt.xlabel("Spatial Error [W/m²]", fontsize=11)
    plt.ylabel("Absolute Global Bias [W/m²]", fontsize=11)
    if last_sc: plt.colorbar(last_sc).set_label(r'Alpha Value ($\alpha$)', fontsize=11)
    
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.tight_layout()
    _handle_show_or_save(output_path)

# ==============================================================================
# EMULATOR VALIDATION
# ==============================================================================
def get_realized_model_map(tag: str, var_name: str, base_2d_dir: str, scratch_dir: str, year1: int, year2: int, target_grid: str = "r180x90") -> xr.DataArray:
    """
    Retrieves the 2D model map from cache or generates it from raw scratch files.

    This helper function avoids redundant I/O and regridding operations by checking
    for pre-computed NetCDF cache files before attempting to process raw OIFS output.

    Args:
        tag: The experiment tag identifier.
        var_name: The target atmospheric variable to extract.
        base_2d_dir: Directory containing cached 2D base NetCDF files.
        scratch_dir: Directory containing the raw model scratch output files.
        year1: The starting year of the evaluation period.
        year2: The ending year of the evaluation period.
        target_grid: Target grid resolution for regridding. Defaults to "r180x90".

    Returns:
        An xarray.DataArray containing the time-averaged, regridded model map.

    Raises:
        FileNotFoundError: If neither the cache nor the raw scratch files exist.
        ImportError: If required regridding dependencies are not installed.
    """
    if compute_derived_flux is None or regrid_to_regular_smm_safe is None:
        raise ImportError("Dependencies for 2D extraction (e.g., 'smmregrid') are missing.")
        
    base_files = glob.glob(os.path.join(base_2d_dir, f"base_2d_{tag}_*_{target_grid}.nc"))
    if base_files:
        ds_base = xr.open_dataset(base_files[0])
        return ds_base[var_name]
        
    print(f"-> Cache missing for {tag}. Extracting raw '{var_name}' from scratch...")
    pattern = os.path.join(scratch_dir, tag, "output", "oifs", f"{tag}_atm_cmip6_1m_*.nc")
    valid_files = [f for f in sorted(glob.glob(pattern)) if year1 <= int(os.path.basename(f).split('_')[-1].split('-')[0]) <= year2]
    
    if not valid_files:
        raise FileNotFoundError(f"Missing scratch files for {tag}")
        
    ds = xr.open_mfdataset(valid_files, combine='nested', concat_dim='time_counter', chunks={'time_counter': 12})
    ds = ds.rename({'time_counter': 'time'}) if 'time_counter' in ds.dims else ds
    
    model_flux = compute_derived_flux(ds, var_name).sel(time=slice(str(year1), str(year2))).mean('time').compute()
    return regrid_to_regular_smm_safe(model_flux, target_grid, method='ycon', raw_file_path=valid_files[0], varname=var_name)

def extract_1d_validation_data(experiment_tags, ecmean_dir, diagnostics_dir, reference_file):
    """
    Extracts the emulator's predictions and actual model results for the 1:1 validation plot.
    
    Args:
        experiment_tags: List of tags identifying the experiments.
        ecmean_dir: Path to the directory containing ECmean output files.
        diagnostics_dir: Path to the directory containing ECtuner diagnostic files.
        reference_file: Path to the YAML file containing reference observations.
        
    Returns:
        A tuple of three dictionaries:
        - Reference observations (keyed by variable).
        - Realized model outputs from ECmean (keyed by tag, then variable).
        - Predicted biases from ECtuner (keyed by tag, then variable).
    """
    ref_obs = {}
    data_ecmean = {}
    data_predicted = {}

    # 1. Extract Reference Observations
    with open(reference_file, 'r') as f:
        ref_raw = yaml.safe_load(f)
        for var, data in ref_raw.items():
            if isinstance(data, dict) and isinstance(data.get('obs'), dict):
                obs = data['obs']
                if isinstance(obs.get('ALL'), dict) and 'Global' in obs['ALL']:
                    ref_obs[var] = obs['ALL']['Global']['mean']

    # 2. Extract Data for each Experiment
    for tag in experiment_tags:
        data_ecmean[tag] = {}
        data_predicted[tag] = {}

        # Read Actual Results (ECmean)
        ecmean_pattern = os.path.join(ecmean_dir, f"*{tag}*.yml")
        ecmean_files = glob.glob(ecmean_pattern)
        
        if ecmean_files:
            with open(ecmean_files[0], 'r') as f:
                ecm_raw = yaml.safe_load(f)
                for var, data in ecm_raw.items():
                    # Applica la stessa logica protettiva qui!
                    if isinstance(data, dict) and isinstance(data.get('ALL'), dict):
                        if 'Global' in data['ALL']:
                            data_ecmean[tag][var] = data['ALL']['Global']
        else:
            print(f"Warning: Missing ECmean file for tag {tag}")

        # Read Emulator Predictions (ECtuner Diagnostics)
        diag_file = os.path.join(diagnostics_dir, f"diagnostics_{tag}.yaml")
        if os.path.exists(diag_file):
            with open(diag_file, 'r') as f:
                diag_raw = yaml.safe_load(f)
                var_metrics = diag_raw.get('var_metrics', {})
                for var, stats in var_metrics.items():
                    # Note: Make sure your diagnostics save 'predicted_global_bias'
                    if 'predicted_global_bias' in stats:
                        data_predicted[tag][var] = stats['predicted_global_bias']
        else:
            print(f"Warning: Missing Diagnostics file for tag {tag}")

    return ref_obs, data_ecmean, data_predicted

def extract_2d_validation_data(tag, var_name, base_2d_dir, scratch_dir, ref_map, year1, year2, target_grid="r180x90", metric='mae'):
    """
    Extracts 2D validation data and computes the spatial cost metric (MAE or RMSE).
    
    Args:
        tag: The experiment tag to evaluate.
        var_name: The name of the variable to extract.
        base_2d_dir: Directory containing cached 2D base netCDF files.
        scratch_dir: Directory containing the raw scratch output files.
        ref_map: The reference data map to compare against.
        year1: The starting year of the evaluation period.
        year2: The ending year of the evaluation period.
        target_grid: The target grid resolution for regridding. Defaults to "r180x90".
        metric: Metric to compute ('mae' for Mean Absolute Error, 'l2' for RMSE). Defaults to 'mae'.
        
    Returns:
        The computed spatial error scalar (float).
    """
    mod_map = get_realized_model_map(tag, var_name, base_2d_dir, scratch_dir, year1, year2, target_grid)
    
    weights = np.cos(np.deg2rad(ref_map.lat))
    
    mod_sorted = mod_map.sortby('lat')
    ref_aligned = ref_map.sortby('lat').reindex_like(mod_sorted, method='nearest')
    error = mod_sorted - ref_aligned
    
    cost = abs(error) if metric.lower() == 'mae' else error**2
    return float(cost.weighted(weights).mean(skipna=True).values ** (0.5 if metric.lower() != 'mae' else 1))


def extract_zonal_validation_data(var_name: str, tag: str, diag_2d_file: str, base_2d_dir: str, scratch_dir: str, ref_2d_file: str, year1: int, year2: int, target_grid: str ="r180x90") -> Tuple[xr.DataArray, xr.DataArray, xr.DataArray, xr.DataArray]:
    """
    Extracts zonal mean profiles for validation comparing initial, predicted, and realized biases.
    
    Args:
        var_name: The name of the variable to analyze.
        tag: The experiment tag.
        diag_2d_file: Path to the 2D diagnostic NetCDF file from the emulator.
        base_2d_dir: Directory containing cached 2D base NetCDF files.
        scratch_dir: Directory containing the raw scratch output files.
        ref_2d_file: Path to the 2D reference observational data file.
        year1: The starting year of the evaluation period.
        year2: The ending year of the evaluation period.
        target_grid: Target grid resolution. Defaults to "r180x90".
        
    Returns:
        A tuple containing arrays for latitudes, initial bias, predicted bias, and realized bias.
    """
    ds_tuner = xr.open_dataset(diag_2d_file)
    zonal_init = ds_tuner[f'{var_name}_bias_init'].mean(dim='lon').sortby('lat')
    zonal_pred = ds_tuner[f'{var_name}_bias_final'].mean(dim='lon').sortby('lat')
    latitudes = ds_tuner.lat.sortby('lat')

    ds_ref = xr.open_dataset(ref_2d_file)
    ref_map = ds_ref[var_name].mean('time') if 'time' in ds_ref.dims else ds_ref[var_name]
    if var_name == 'rlnt' and float(ref_map.mean()) > 0:
        ref_map = -1.0 * ref_map

    mod_map = get_realized_model_map(tag, var_name, base_2d_dir, scratch_dir, year1, year2, target_grid)

    mod_sorted = mod_map.sortby('lat')
    ref_aligned = ref_map.sortby('lat').reindex_like(mod_sorted, method='nearest')
    zonal_realized = (mod_sorted - ref_aligned).mean(dim='lon')

    return latitudes, zonal_init, zonal_pred, zonal_realized

def plot_emulator_performance_global(var_name: str, ref_obs: Dict[str, float], data_ecmean: Dict[str, Dict[str, float]], data_predicted_bias: Dict[str, Dict[str, float]], base_bias: float = None, output_path: str = None, color_mapping: dict = None) -> None:
    """
    1:1 Validation test of the Emulator's global bias prediction against actual EC-Earth outputs.

    Args:
        var_name: Target variable to validate.
        ref_obs: Reference observations.
        data_ecmean: Realized biases from the model run.
        data_predicted_bias: Biases predicted by ECtuner.
        output_path: Optional file path to save the plot.
    """
    alphas = sorted(list(data_ecmean.keys()))
    realized_biases = [data_ecmean[a][var_name] - ref_obs[var_name] for a in alphas]
    predicted_biases = [data_predicted_bias[a][var_name] for a in alphas]

    plt.figure(figsize=(6.5, 6.5))
    default_colors = ['#e41a1c', '#4daf4a', '#377eb8', '#984ea3', '#ff7f00', '#ffff33']
    
    for i, a in enumerate(alphas):
        lab = a.replace('_', ' = ').title().replace('Alpha', r'$\alpha$')
        color = color_mapping.get(a, default_colors[i % len(default_colors)]) if color_mapping else default_colors[i % len(default_colors)]

        plt.scatter(predicted_biases[i], realized_biases[i], color=color, s=130, label=lab, edgecolors='black', zorder=5)

    lims = [min(predicted_biases + realized_biases) - 0.5, max(predicted_biases + realized_biases) + 0.5]
    plt.plot(lims, lims, 'k--', alpha=0.5, label='1:1 Ideal Line')

    if base_bias is not None:
        plt.scatter(base_bias, base_bias, color='gold', s=350, marker='*', edgecolors='black', zorder=6, label='Initial (Base Model)')
    
    plt.xlabel(f'Predicted {var_name.upper()} Global Bias [W/m²]', fontsize=11)
    plt.ylabel(f'Realized {var_name.upper()} Global Bias (Model - CERES) [W/m²]', fontsize=11)
    plt.title(f'Global Bias Validation: Emulator vs Model\nVariable: {var_name.upper()}', fontsize=12, fontweight='bold')
    
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.legend(loc='upper left')
    plt.axis('equal')
    plt.tight_layout()
    if output_path: plt.savefig(output_path, dpi=300)
    else: plt.show()

def plot_emulator_vs_model_spatial(var_name: str, preds_dict: Dict[str, float], reals_dict: Dict[str, float], base_cost: float = None, output_path: str = None, color_mapping: dict = None) -> None:
    """
    Performance 1:1 test validating emulator spatial predictions against realized outputs.

    Args:
        var_name: Target variable to validate.
        preds_dict: Dictionary mapping run tags/alphas to predicted errors.
        reals_dict: Dictionary mapping run tags/alphas to actual realized errors.
        output_path: Optional file path to save the plot.
        color_mapping: Optional dictionary mapping alpha values to colors.
    """
    alphas = sorted(list(preds_dict.keys()))
    x_vals = [preds_dict[a] for a in alphas]
    y_vals = [reals_dict[a] for a in alphas]

    plt.figure(figsize=(6.5, 6.5))
    default_colors = ['#e41a1c', '#4daf4a', '#377eb8', '#984ea3', '#ff7f00', '#ffff33']

    for i, a in enumerate(alphas):
        lab = a.replace('_', ' = ').title().replace('Alpha', r'$\alpha$')
        color = color_mapping.get(a, default_colors[i % len(default_colors)]) if color_mapping else default_colors[i % len(default_colors)]
        plt.scatter(x_vals[i], y_vals[i], color=color, s=130, label=lab, edgecolors='black', zorder=5)

    all_vals = x_vals + y_vals
    margin = (max(all_vals) - min(all_vals)) * 0.2 if len(all_vals) > 1 else 1.0
    lims = [min(all_vals) - margin, max(all_vals) + margin]
    plt.plot(lims, lims, color='gray', linestyle='--', alpha=0.6, label='1:1 Perfect Line')

    if base_cost is not None:
        plt.scatter(base_cost, base_cost, color='gold', s=350, marker='*', edgecolors='black', zorder=6, label='Initial (Base Model)')

    plt.xlabel('Spatial Cost Predicted (Emulator) [W/m²]', fontsize=11)
    plt.ylabel('Spatial Cost Realized (Model) [W/m²]', fontsize=11)
    plt.title(f'Spatial Validation: Emulator vs Model\nVariable: {var_name.upper()}', fontsize=12, fontweight='bold')
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.legend(loc='upper left')
    plt.axis('equal')
    plt.tight_layout()
    _handle_show_or_save(output_path)

def plot_zonal_validation(latitudes: xr.DataArray, zonal_init: xr.DataArray, zonal_pred: xr.DataArray, zonal_realized: xr.DataArray, exp_tag: str, var_name: str, output_path: str = None) -> None:
    """
    Plots the zonal profile validation comparing initial, predicted, and realized biases.
    
    Args:
        latitudes: Latitude coordinates array.
        zonal_init: The initial zonal bias mean array.
        zonal_pred: The predicted final zonal bias mean array.
        zonal_realized: The actual realized zonal bias mean array.
        exp_tag: The experiment tag identifier.
        var_name: The name of the variable being plotted.
        output_path: Optional file path to save the plot.
    """
    fig, ax = plt.subplots(figsize=(5.5, 8))
    ax.axvline(0, color='black', lw=1, alpha=0.4)
    
    ax.plot(zonal_init, latitudes, label='Initial Bias (Base)', color='orange', linestyle='--', lw=1.8)
    ax.plot(zonal_pred, latitudes, label='Predicted Final (Emulator)', color='blue', linestyle=':', lw=2.2)
    ax.plot(zonal_realized, latitudes, label=f'Realized Final ({exp_tag})', color='green', lw=2.5)
    
    ax.set_title(f'{var_name.upper()} Zonal Bias Validation\nRun: {exp_tag}', fontsize=12, fontweight='bold')
    ax.set_xlabel('Bias wrt Reference [W/m²]', fontsize=11)
    ax.set_ylabel('Latitude', fontsize=11)
    ax.grid(True, linestyle=':', alpha=0.5)
    ax.legend(loc='upper right', fontsize=9)
    ax.set_ylim(-90, 90)
    plt.tight_layout()
    _handle_show_or_save(output_path)

def plot_bias_decomposition(diag_yaml_path: str, diag_nc_path: str, sens_nc_path: str, var_name: str, exp_tag: str = "", output_path: str = None) -> dict:
    """
    Decomposes the predicted global bias into individual parameter contributions.
    
    Args:
        diag_yaml_path: Path to the diagnostics_*.yaml file.
        diag_nc_path: Path to the diagnostics_2d_*.nc file.
        sens_nc_path: Path to the 2D sensitivity NetCDF file.
        var_name: The name of the variable (e.g., 'rsnt' or 'rlnt').
        exp_tag: Experiment tag for the title (e.g., 'C200').
        output_path: Optional path to save the generated plot.
        
    Returns:
        A dictionary mapping parameters to their predicted global flux contribution.
    """
    import math

    # 1. Load data
    with open(diag_yaml_path, 'r') as f:
        diag_data = yaml.safe_load(f)
        
    ds_diag = xr.open_dataset(diag_nc_path)
    ds_sens = xr.open_dataset(sens_nc_path)
    
    bias_init_name = f'{var_name}_bias_init'
    if bias_init_name not in ds_diag.data_vars:
        print(f"Variable {bias_init_name} not found in {diag_nc_path}")
        return {}

    bias_init_map = ds_diag[bias_init_name]
    
    # 2. Extract optimal changes (Delta p)
    optimal_changes = {p['name']: float(p['change_abs']) for p in diag_data['parameters']}
        
    # 3. Calculate spatial weights (cosine of latitude)
    weights = np.cos(np.deg2rad(bias_init_map.lat))
    global_bias_init = float(bias_init_map.weighted(weights).mean())
    
    contributions = {}
    
    # 4. Reconstruct individual global contributions
    for p, delta_p in optimal_changes.items():
        if p in ds_sens.parameter.values and var_name in ds_sens.variable.values:
            slope_map = ds_sens.sel(variable=var_name, parameter=p).slope
            delta_flux_map = slope_map * delta_p
            global_contrib = float(delta_flux_map.weighted(weights).mean(skipna=True))
            contributions[p] = global_contrib
            
    sorted_contribs = dict(sorted(contributions.items(), key=lambda item: abs(item[1])))
    
    params = list(sorted_contribs.keys())
    vals = list(sorted_contribs.values())
    
    # 5. Plotting
    plt.figure(figsize=(10, 8))
    bars = plt.barh(params, vals, color=['#d73027' if v > 0 else '#4575b4' for v in vals])
    plt.axvline(0, color='black', linewidth=1.2, linestyle='--')
    
    for bar in bars:
        width = bar.get_width()
        ha = 'left' if width > 0 else 'right'
        offset = 0.05 if width > 0 else -0.05
        if abs(width) > 0.01:
            plt.text(width + offset, bar.get_y() + bar.get_height()/2, 
                     f'{width:.2f}', va='center', ha=ha, fontsize=9)
    
    predicted_total = global_bias_init + sum(vals)
    
    plt.title(f"[{exp_tag}] Bias Decomposition: {var_name.upper()}", fontsize=14, fontweight='bold')
    plt.xlabel("Predicted Contribution to Global Flux [W/m²]", fontsize=12)
    
    info_text = (f"Initial Bias: {global_bias_init:+.2f} W/m²\n"
                 f"Sum of Contributions: {sum(vals):+.2f} W/m²\n"
                 f"Predicted Final Bias: {predicted_total:+.2f} W/m²")
    
    plt.text(0.95, 0.05, info_text, transform=plt.gca().transAxes, fontsize=11,
             verticalalignment='bottom', horizontalalignment='right',
             bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
    
    plt.grid(axis='x', linestyle=':', alpha=0.6)
    plt.tight_layout()
    _handle_show_or_save(output_path)
    
    return sorted_contribs


def plot_sensitivity_maps(sens_nc_path: str, var_name: str, ref_values: dict, inc: float = 0.3, vmin: float = -3.0, vmax: float = 3.0, output_path: str = None) -> None:
    """
    Creates a composite map of all spatial sensitivities for a specific variable.
    
    Args:
        sens_nc_path: Path to the 2D sensitivity NetCDF file.
        var_name: The target atmospheric variable (e.g., 'rsnt').
        vmin: Minimum value for the color scale.
        vmax: Maximum value for the color scale.
        output_path: Optional path to save the generated plot.
    """
    import math

    ds_sens = xr.open_dataset(sens_nc_path)
    
    if var_name not in ds_sens.variable.values:
        print(f"Variable {var_name} not found in {sens_nc_path}")
        return
        
    ds_var = ds_sens.sel(variable=var_name)
    parameters = ds_var.parameter.values
    
    n = len(parameters)
    ncols = math.ceil(math.sqrt(n))
    nrows = math.ceil(n / ncols)
    
    fig, axs = plt.subplots(
        nrows, ncols,
        figsize=(4 * ncols, 2.5 * nrows),
        subplot_kw={'projection': ccrs.PlateCarree()}
    )
    
    if nrows * ncols > 1:
        axs = axs.flatten()
    else:
        axs = [axs]
        
    for i, param in enumerate(parameters):
        ax = axs[i]
        field = ds_var.sel(parameter=param).slope
        
        # Handle extra dimensions if present
        extra_dims = [d for d in field.dims if d not in ['lat', 'lon']]
        if extra_dims:
            field = field.mean(extra_dims)
            
        p_ref = ref_values.get(param, 1.0)
        delta_p = abs(p_ref) * inc if p_ref != 0 else inc 
        data = field.values * delta_p
        lon2d, lat2d = np.meshgrid(field['lon'], field['lat'])
        
        im = ax.pcolormesh(
            lon2d, lat2d, data,
            vmin=vmin, vmax=vmax, cmap='RdBu_r',
            transform=ccrs.PlateCarree(),
            shading="auto"
        )
        
        ax.coastlines(linewidth=0.5)
        ax.set_title(param, fontsize=12)
        
    for ax in axs[len(parameters):]:
        ax.remove()
        
    cbar_ax = fig.add_axes([0.25, 0.08, 0.5, 0.03])
    cbar = fig.colorbar(im, cax=cbar_ax, orientation='horizontal')
    cbar.set_label(f'Impact on {var_name.upper()} for {inc*100}% param change (W/m²)')
    
    _handle_show_or_save(output_path)

import math
def plot_sensitivity_maps_with_snr(sens_nc_path: str, path_ctrl: str, var_name: str, ref_values: dict, inc: float = 0.3, snr_threshold: float = 1.0, vmin: float = -3.0, vmax: float = 3.0, output_path: str = None) -> None:
    """
    Creates a composite map of all spatial sensitivities for a specific variable, applying a filter based on the Signal-to-Noise Ratio (SNR).
    """
    # 1. compute the noise map from the control run
    print("Calcolo la mappa del rumore dal run di controllo...")
    ds_ctrl = xr.open_mfdataset(path_ctrl, chunks={'time_counter': 12})
    
    if var_name == 'net_toa' and 'net_toa' not in ds_ctrl:
        ds_ctrl['net_toa'] = ds_ctrl['rsdt'] - ds_ctrl['rsut'] - ds_ctrl['rlut']
        
    noise_map_raw = ds_ctrl[var_name].groupby('time_counter.year').mean().std(dim='year').compute()
    noise_map_raw.name = var_name 
    
    sample_raw_file = glob.glob(path_ctrl)[0]
    noise_map = regrid_to_regular_smm_safe(
        ds_averaged=noise_map_raw,
        target_grid='r180x90',
        method='ycon',
        raw_file_path=sample_raw_file,
        varname=var_name
    )

    ds_sens = xr.open_dataset(sens_nc_path)
    if var_name not in ds_sens.variable.values:
        print(f"Variabile {var_name} non trovata in {sens_nc_path}")
        return
        
    ds_var = ds_sens.sel(variable=var_name)
    parameters = ds_var.parameter.values
    
    n = len(parameters)
    ncols = math.ceil(math.sqrt(n))
    nrows = math.ceil(n / ncols)
    
    fig, axs = plt.subplots(
        nrows, ncols,
        figsize=(4 * ncols, 2.5 * nrows),
        subplot_kw={'projection': ccrs.PlateCarree()}
    )
    if nrows * ncols > 1:
        axs = axs.flatten()
    else:
        axs = [axs]
        
    for i, param in enumerate(parameters):
        ax = axs[i]
        field = ds_var.sel(parameter=param).slope
        
        extra_dims = [d for d in field.dims if d not in ['lat', 'lon']]
        if extra_dims:
            field = field.mean(extra_dims)
            
        p_ref = ref_values.get(param, 1.0)
        delta_p = abs(p_ref) * inc if p_ref != 0 else inc 
        
        signal = np.abs(field * delta_p)
        snr = signal / noise_map
        
        data_filtered = xr.where(snr > snr_threshold, field * delta_p, 0.0)
        data = data_filtered.values
        
        lon2d, lat2d = np.meshgrid(field['lon'], field['lat'])
        
        im = ax.pcolormesh(
            lon2d, lat2d, data,
            vmin=vmin, vmax=vmax, cmap='RdBu_r',
            transform=ccrs.PlateCarree(),
            shading="auto"
        )
        ax.coastlines(linewidth=0.5)
        ax.set_title(param, fontsize=12)
        
    for ax in axs[len(parameters):]:
        ax.remove()
        
    cbar_ax = fig.add_axes([0.25, 0.08, 0.5, 0.03])
    cbar = fig.colorbar(im, cax=cbar_ax, orientation='horizontal')
    cbar.set_label(f'Robust Impact on {var_name.upper()} (SNR > {snr_threshold}) (W/m²)')
    
    if output_path:
        plt.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"Plot salvato in: {output_path}")
    else:
        plt.show()
    plt.close()