"""
Diagnostic Visualization Module.

Reads structured diagnostic YAML files generated by ECtuner and creates
visualizations for parameter changes, score evolution, bias reduction,
and Pareto front tradeoffs.
"""
import os
import glob
import yaml
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import cartopy.crs as ccrs
import xarray as xr
from pathlib import Path
from typing import Dict, Any, List

# Try importing the regridder for validation plots from scratch
try:
    from .utils import regrid_to_regular_smm_safe, compute_derived_flux
except ImportError:
    regrid_to_regular_smm_safe = None
    compute_derived_flux = None

def _handle_show_or_save(output_path=None):
    """Internal helper to handle plot saving or showing cleanly."""
    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        plt.savefig(output_path, dpi=300, bbox_inches='tight')
        print(f"Plot saved successfully to: {output_path}")
    else:
        plt.show()
    plt.close()

def load_diagnostic_yamls(folder_path: str) -> Dict[str, Any]:
    """
    Scans a folder for ECtuner diagnostic files and loads them.

    Args:
        folder_path: Path to the directory containing diagnostics YAMLs.

    Returns:
        A dictionary mapping experiment tags to their parsed diagnostic data.
        
    Raises:
        FileNotFoundError: If the specified folder does not exist.
    """
    folder = Path(folder_path)
    if not folder.exists():
        raise FileNotFoundError(f"Folder not found: {folder_path}")

    diag_data = {}
    files = sorted(folder.glob("diagnostics_*.yaml"))

    for filepath in files:
        tag = filepath.stem.replace("diagnostics_", "")
        with open(filepath, 'r') as f:
            diag_data[tag] = yaml.safe_load(f)
            
    print(f"Loaded {len(diag_data)} diagnostic files from {folder_path}")
    return diag_data


def build_metrics_dataframe(diag_data: Dict[str, Any]) -> pd.DataFrame:
    """
    Converts the nested YAML dictionary into a Pandas DataFrame optimized 
    for Pareto front and Tradeoff plotting.

    Args:
        diag_data: Data loaded via load_diagnostic_yamls.

    Returns:
        A DataFrame containing sorted metrics for all experiments.
    """
    records = []
    
    for exp_tag, data in diag_data.items():
        metrics = data.get('metrics', {})
        record = {
            'Experiment': exp_tag,
            'Alpha': metrics.get('alpha', np.nan),
            'Metric': metrics.get('metric_name', 'l2'),
            'Raw_Spatial_Cost': metrics.get('total_spatial_cost', np.nan),
            'Raw_Global_Cost': metrics.get('total_global_cost', np.nan),
        }
        
        # Determine Physical Units based on metric type
        if record['Metric'] == 'l2':
            record['Metric_Type'] = 'L2 (Quadratic)'
            record['Phys_Spatial_Total'] = np.sqrt(record['Raw_Spatial_Cost'])
            record['Phys_Global_Total'] = np.sqrt(record['Raw_Global_Cost'])
        else:
            record['Metric_Type'] = 'L1 (Linear)'
            record['Phys_Spatial_Total'] = record['Raw_Spatial_Cost']
            record['Phys_Global_Total'] = record['Raw_Global_Cost']
            
        # Extract Variable-Specific Biases from the 'biases' block if needed
        # Assuming the structure is: biases -> targets -> list of dicts
        targets = data.get('biases', {}).get('targets', [])
        for t in targets:
            var = t['variable']
            if t['region'] == 'Global':
                record[f'{var}_AbsBias'] = abs(t['bias_final'])

        var_metrics = data.get('var_metrics', {})
        for var_name, stats in var_metrics.items():
            record[f'{var_name}_Spatial_Cost'] = stats.get('spatial_cost', np.nan)
                
        records.append(record)
        
    df = pd.DataFrame(records)
    if not df.empty:
        df.set_index('Experiment', inplace=True)
        df.sort_values(by='Alpha', inplace=True)
        
    return df

# ==============================================================================
def plot_parameter_scatter(diag_data: Dict[str, Any], output_path: str = None) -> None:
    """
    Creates a scatter plot with parameters on the x-axis and relative value.

    Args:
        diag_data: Dictionary containing loaded diagnostic data.
        output_path: Optional file path to save the plot.
    """
    if not diag_data:
        print("No data to plot")
        return

    params_set = set()
    for data in diag_data.values():
        for p in data['parameters']:
            params_set.add(p['name'])
    all_params = sorted(list(params_set))

    fig, ax = plt.subplots(figsize=(max(12, len(all_params) * 0.8), 8))
    
    exp_names = list(diag_data.keys())
    colors = plt.cm.tab10(np.linspace(0, 1, len(exp_names)))
    
    for exp_idx, exp_name in enumerate(exp_names):
        x_positions = []
        y_values = []
        
        for param_idx, param_name in enumerate(all_params):
            param_data = next((p for p in diag_data[exp_name]['parameters'] if p['name'] == param_name), None)
            
            if param_data and float(param_data['ref_value']) != 0:
                x_positions.append(param_idx)
                y_values.append(float(param_data['new_value']) / float(param_data['ref_value']))
        
        ax.scatter(x_positions, y_values, s=100, alpha=0.7, 
                   color=colors[exp_idx], label=exp_name, zorder=3)
    
    
    ax.axhline(y=1, color='black', linestyle='--', alpha=0.5, linewidth=1)
    
    ax.set_xticks(range(len(all_params)))
    ax.set_xticklabels(all_params, rotation=45, ha='right')
    ax.set_ylabel('Relative value (with respect to default)', fontsize=12)
    ax.set_xlabel('Parameters', fontsize=12)
    
    ax.legend(bbox_to_anchor=(1.02, 1), loc='upper left')
    ax.grid(True, alpha=0.3)
    
    plt.tight_layout()
    _handle_show_or_save(output_path)

def plot_parameter_heatmap(diag_data: Dict[str, Any], output_path: str = None) -> None:
    """
    Creates a heatmap showing the normalized relative change of parameters.

    Args:
        diag_data: Dictionary containing loaded diagnostic data.
        output_path: Optional file path to save the plot.
    """
    if not diag_data:
        return

    data_matrix = {}
    for exp_tag, data in diag_data.items():
        data_matrix[exp_tag] = {}
        for p in data['parameters']:
            if float(p['ref_value']) != 0:
                rel_change = (float(p['new_value']) - float(p['ref_value'])) / float(p['ref_value'])
                data_matrix[exp_tag][p['name']] = rel_change
    df = pd.DataFrame(data_matrix).T

    fig, ax = plt.subplots(figsize=(max(12, len(df.columns) * 0.8), max(4, len(df) * 0.6)))
    
    im = ax.imshow(df.values, aspect='auto', cmap='RdBu_r', vmin=-0.5, vmax=0.5)
    
    ax.set_xticks(np.arange(len(df.columns)))
    ax.set_xticklabels(df.columns, rotation=45, ha='right')
    ax.set_yticks(np.arange(len(df.index)))
    ax.set_yticklabels(df.index)

    plt.colorbar(im, ax=ax, label='Relative change')

    for i in range(len(df.index)):
        for j in range(len(df.columns)):
            val = df.iloc[i, j]
            if not np.isnan(val):
                text_color = "white" if abs(val) > 0.25 else "black"
                ax.text(j, i, f'{val:.2e}', ha="center", va="center", color=text_color, fontsize=8)

    plt.tight_layout()
    _handle_show_or_save(output_path)

# ==============================================================================
# ==============================================================================

def compute_diagnostic_metrics(ds: xr.Dataset, var: str):
    """Zonal metrics and plots limits for a given variable from the diagnostic NetCDF."""
    b_init = ds[f'{var}_bias_init']
    b_final = ds[f'{var}_bias_final']
    improv = ds[f'{var}_improvement']

    vmax = float(max(abs(b_init).max().item(), abs(b_final).max().item()))
    vmin = -vmax
    
    zonal_init = b_init.mean(dim='lon')
    zonal_final = b_final.mean(dim='lon')
    
    return b_init, b_final, improv, vmin, vmax, zonal_init, zonal_final

def plot_tuning_results_maps(diag_file: str, output_dir: str, run_tag: str) -> None:
    """
    Generates 2D maps comparing Initial Bias vs Final Predicted Bias from the diagnostic NetCDF.

    Args:
        diag_file: Path to the diagnostic NetCDF file.
        output_dir: Directory to save the output plots.
        run_tag: Identifier for the current experiment run.
    """
    ds = xr.open_dataset(diag_file)
    variables = [v.replace('_bias_init', '') for v in ds.data_vars if '_bias_init' in v]
    
    for var in variables:

        b_init, b_final, improv, vmin, vmax, zonal_init, zonal_final = compute_diagnostic_metrics(ds, var)

        fig = plt.figure(figsize=(24, 5))
        gs = fig.add_gridspec(1, 4, width_ratios=[1, 1, 1, 0.6])

        ax0 = fig.add_subplot(gs[0], projection=ccrs.PlateCarree())
        ax1 = fig.add_subplot(gs[1], projection=ccrs.PlateCarree())
        ax2 = fig.add_subplot(gs[2], projection=ccrs.PlateCarree())
        ax_zonal = fig.add_subplot(gs[3])
        
        im0 = b_init.plot(ax=ax0, transform=ccrs.PlateCarree(), cmap='RdBu_r', vmin=vmin, vmax=vmax, add_colorbar=False)
        ax0.set_title(f'{var} - Initial Bias')
        
        im1 = b_final.plot(ax=ax1, transform=ccrs.PlateCarree(), cmap='RdBu_r', vmin=vmin, vmax=vmax, add_colorbar=False)
        ax1.set_title(f'{var} - Final Bias (Predicted)')
        
        im2 = improv.plot(ax=ax2, transform=ccrs.PlateCarree(), cmap='PiYG', add_colorbar=False)
        ax2.set_title(f'{var} - Absolute Improvement')
        
        for ax in [ax0, ax1, ax2]:
            ax.coastlines()
            
        fig.colorbar(im1, ax=[ax0, ax1], location='bottom', label='Bias Units', fraction=0.05, pad=0.08)
        fig.colorbar(im2, ax=[ax2], location='bottom', label='Improvement', fraction=0.05, pad=0.08)

        ax_zonal.plot(zonal_init, ds.lat, label='Init (Red)', color='red', linestyle='--', lw=1.5)
        ax_zonal.plot(zonal_final, ds.lat, label='Final (Blue)', color='blue', lw=2)
        ax_zonal.axvline(0, color='black', lw=0.8, alpha=0.5)
        ax_zonal.set_title(f'{var} Zonal Bias')
        ax_zonal.legend(fontsize='small', loc='upper right')
        ax_zonal.grid(True, alpha=0.3)
        
        plot_name = f"comparison_2d_{var}_{run_tag}.png"
        os.makedirs(output_dir, exist_ok=True)
        plt.savefig(os.path.join(output_dir, plot_name), bbox_inches='tight', dpi=150)
        plt.close()

# ==============================================================================
def plot_tradeoff_comparison(df: pd.DataFrame, group_by: str = 'Metric_Type', output_path: str = None) -> None:
    """
    Global Pareto front plot: spatial error vs global bias.
    Allows dynamic grouping.

    Args:
        df: DataFrame built from diagnostic data.
        group_by: Column name to group markers by.
        output_path: Optional file path to save the plot.
    """
    plt.figure(figsize=(9, 6.5))
    
    markers = ['o', 's', '^', 'D', 'v', 'P']
    last_sc = None
    legend_elements = []

    if group_by not in df.columns:
        df[group_by] = 'All Data'

    metrics_present = df['Metric'].unique() if 'Metric' in df.columns else []
    title_suffix = "(RMSE/MAE & Abs Bias)" if len(metrics_present) > 1 else ("(RMSE & Abs Bias)" if 'l2' in metrics_present else "(MAE & Abs Bias)")

    for i, group_name in enumerate(df[group_by].unique()):
        subset = df[df[group_by] == group_name].dropna(subset=['Phys_Spatial_Total', 'Phys_Global_Total']).sort_values('Alpha')
        if subset.empty: continue
        
        mkr = markers[i % len(markers)]
        last_sc = plt.scatter(subset['Phys_Spatial_Total'], subset['Phys_Global_Total'], 
                              c=subset['Alpha'], cmap='viridis', marker=mkr, s=140, edgecolors='black', zorder=3, vmin=0, vmax=1)
        plt.plot(subset['Phys_Spatial_Total'], subset['Phys_Global_Total'], linestyle='--', alpha=0.4, zorder=2)
        
        for _, row in subset.iterrows():
            plt.annotate(fr'$\alpha$={row["Alpha"]:.2f}', (row['Phys_Spatial_Total'], row['Phys_Global_Total']),
                         xytext=(5, 5), textcoords='offset points', fontsize=8, alpha=0.7)

        legend_elements.append(
            Line2D([0], [0], marker=mkr, color='w', label=str(group_name), 
                   markerfacecolor='gray', markersize=10, markeredgecolor='black')
        )
    
    legend_title = group_by.replace('_', ' ')
    plt.legend(handles=legend_elements, loc='upper right', title=legend_title)
    plt.title(f"Pareto Front: Total Spatial Error vs Total Global Bias\nUnits: {title_suffix}", fontsize=12, fontweight='bold')
    plt.xlabel("Total Spatial Error (Physical Units)", fontsize=11)
    plt.ylabel("Total Global Bias (Physical Units)", fontsize=11)
    
    if last_sc: plt.colorbar(last_sc).set_label(r'Alpha Value ($\alpha$)', fontsize=11)
    
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.tight_layout()
    _handle_show_or_save(output_path)

def plot_variable_pareto(df: pd.DataFrame, var: str, group_by: str = 'Metric_Type', output_path: str = None) -> None:
    """
    Pareto Front specific to a single atmospheric variable.

    Args:
        df: DataFrame built from diagnostic data.
        var: The specific atmospheric variable to plot (e.g., 'net_toa').
        group_by: Column name to group markers by.
        output_path: Optional file path to save the plot.
    """
    plt.figure(figsize=(9, 6.5))
    
    col_bias = f'{var}_AbsBias'
    col_spat = f'{var}_Spatial_Cost'

    if col_bias not in df.columns:
        print(f"Variable {var} not found in DataFrame for Pareto plot.")
        return
    
    markers = ['o', 's', '^', 'D', 'v', 'P']
    last_sc = None
    legend_elements = []

    if group_by not in df.columns:
        df[group_by] = 'All Data'

    for i, group_name in enumerate(df[group_by].unique()):
        subset = df[df[group_by] == group_name].dropna(subset=[col_spat, col_bias]).sort_values('Alpha')
        if subset.empty: continue
        
        mkr = markers[i % len(markers)]
        last_sc = plt.scatter(subset[col_spat], subset[col_bias], 
                              c=subset['Alpha'], cmap='viridis', marker=mkr, s=140, edgecolors='black', zorder=3, vmin=0, vmax=1)
        plt.plot(subset[col_spat], subset[col_bias], linestyle='--', alpha=0.4, zorder=2)
        
        for _, row in subset.iterrows():
            plt.annotate(fr'$\alpha$={row["Alpha"]:.2f}', (row[col_spat], row[col_bias]),
                         xytext=(5, 5), textcoords='offset points', fontsize=8, alpha=0.7)

        legend_elements.append(
            Line2D([0], [0], marker=mkr, color='w', label=str(group_name), 
                   markerfacecolor='gray', markersize=10, markeredgecolor='black')
        )

    legend_title = group_by.replace('_', ' ')
    plt.legend(handles=legend_elements, loc='upper right', title=legend_title)
        
    plt.title(f"Pareto Front: Spatial Error vs Global Bias ({var.upper()})", fontsize=12, fontweight='bold')
    plt.xlabel("Spatial Error [W/m²]", fontsize=11)
    plt.ylabel("Absolute Global Bias [W/m²]", fontsize=11)
    if last_sc: plt.colorbar(last_sc).set_label(r'Alpha Value ($\alpha$)', fontsize=11)
    
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.tight_layout()
    _handle_show_or_save(output_path)

# ==============================================================================
def plot_emulator_performance_global(var_name: str, ref_obs: Dict[str, float], data_ecmean: Dict[str, Dict[str, float]], data_predicted_bias: Dict[str, Dict[str, float]], output_path: str = None) -> None:
    """
    1:1 Validation test of the Emulator's global bias prediction against actual EC-Earth outputs.

    Args:
        var_name: Target variable to validate.
        ref_obs: Reference observations.
        data_ecmean: Realized biases from the model run.
        data_predicted_bias: Biases predicted by ECtuner.
        output_path: Optional file path to save the plot.
    """
    alphas = list(data_ecmean.keys())
    realized_biases = [data_ecmean[a][var_name] - ref_obs[var_name] for a in alphas]
    predicted_biases = [data_predicted_bias[a][var_name] for a in alphas]

    plt.figure(figsize=(6.5, 6.5))
    colors = ['#e41a1c', '#4daf4a', '#377eb8', '#984ea3', '#ff7f00', '#ffff33'][:len(alphas)]
    
    for i, a in enumerate(alphas):
        lab = a.replace('_', ' = ').title().replace('Alpha', r'$\alpha$')
        plt.scatter(predicted_biases[i], realized_biases[i], color=colors[i], s=130, label=lab, edgecolors='black', zorder=5)

    lims = [min(predicted_biases + realized_biases) - 0.5, max(predicted_biases + realized_biases) + 0.5]
    plt.plot(lims, lims, 'k--', alpha=0.5, label='1:1 Ideal Line')
    
    plt.xlabel(f'Predicted {var_name.upper()} Global Bias [W/m²]', fontsize=11)
    plt.ylabel(f'Realized {var_name.upper()} Global Bias (Model - CERES) [W/m²]', fontsize=11)
    plt.title(f'Global Bias Validation: Emulator vs Model\nVariable: {var_name.upper()}', fontsize=12, fontweight='bold')
    
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.legend(loc='upper left')
    plt.axis('equal')
    plt.tight_layout()
    if output_path: plt.savefig(output_path, dpi=300)
    else: plt.show()

def plot_emulator_vs_model_spatial(var_name, preds_dict, reals_dict, output_path=None):
    """
    Performance 1:1 test (MAE) validating emulator spatial predictions against realized outputs.

    Args:
        var_name: Target variable to validate.
        preds_dict: Dictionary mapping alphas to predicted MAE.
        reals_dict: Dictionary mapping alphas to realized MAE.
        output_path: Optional file path to save the plot.
    """
    alphas = list(preds_dict.keys())
    x_vals = [preds_dict[a] for a in alphas]
    y_vals = [reals_dict[a] for a in alphas]

    plt.figure(figsize=(6.5, 6.5))
    colors = ['#e41a1c', '#4daf4a', '#377eb8', '#984ea3', '#ff7f00', '#ffff33'][:len(alphas)]

    for i, a in enumerate(alphas):
        lab = a.replace('_', ' = ').title().replace('Alpha', r'$\alpha$')
        plt.scatter(x_vals[i], y_vals[i], color=colors[i], s=130, label=lab, edgecolors='black', zorder=5)

    all_vals = x_vals + y_vals
    margin = (max(all_vals) - min(all_vals)) * 0.2 if len(all_vals) > 1 else 1.0
    lims = [min(all_vals) - margin, max(all_vals) + margin]
    plt.plot(lims, lims, color='gray', linestyle='--', alpha=0.6, label='1:1 Perfect Line')

    plt.xlabel('Spatial MAE Predicted (Emulator) [W/m²]', fontsize=11)
    plt.ylabel('Spatial MAE Realized (Model) [W/m²]', fontsize=11)
    plt.title(f'Spatial MAE Validation: Emulator vs Model\nVariable: {var_name.upper()}', fontsize=12, fontweight='bold')
    plt.grid(True, linestyle=':', alpha=0.5)
    plt.legend(loc='upper left')
    plt.axis('equal')
    plt.tight_layout()
    _handle_show_or_save(output_path)

def plot_zonal_validation_from_scratch(tuner_diag_file, scratch_dir, exp_tag, year1, year2, ceres_file, var_tuner, output_path=None):
    """
    Cross-Validation zonal profile (Initial vs Predicted vs Realized).
    
    Args:
        tuner_diag_file: NetCDF output from ECtuner.
        scratch_dir: Directory containing raw EC-Earth output files.
        exp_tag: Experiment ID (e.g., 'aa00').
        year1: Start year for climatology.
        year2: End year for climatology.
        ceres_file: Path to CERES observational dataset.
        var_tuner: Variable to validate.
        output_path: Optional file path to save the plot.
    """
    if regrid_to_regular_smm_safe is None or compute_derived_flux is None:
        raise ImportError("Dipendencies for zonal validation ('smmregrid', ecc.) not available.")

    ds_tuner = xr.open_dataset(tuner_diag_file)
    tuner_init = ds_tuner[f'{var_tuner}_bias_init'].mean(dim='lon').sortby('lat')
    tuner_pred = ds_tuner[f'{var_tuner}_bias_final'].mean(dim='lon').sortby('lat')
    lat_tuner = ds_tuner.lat.sortby('lat')

    files = sorted(glob.glob(os.path.join(scratch_dir, f"{exp_tag}_atm_cmip6_1m_*.nc")))
    valid_files = [f for f in files if year1 <= int(os.path.basename(f).split('_')[-1].split('-')[0]) <= year2]
    
    ds_model = xr.open_mfdataset(valid_files, combine='nested', concat_dim='time_counter', chunks={'time_counter': 12})
    if 'time_counter' in ds_model.dims: ds_model = ds_model.rename({'time_counter': 'time'})

    model_flux = compute_derived_flux(ds_model, var_tuner).mean('time').compute()
    model_reg = regrid_to_regular_smm_safe(model_flux, 'r180x90', method='ycon', raw_file_path=valid_files[0], varname=var_tuner)

    ceres = xr.open_dataset(ceres_file).interp(lat=model_reg.lat)
    ceres_flux = ceres['toa_net_all_mon'] if var_tuner == 'net_toa' else (ceres['solar_mon'] - ceres['toa_sw_all_mon'] if var_tuner == 'rsnt' else -1.0 * ceres['toa_lw_all_mon'])

    model_zonal_realized = (model_reg - ceres_flux).mean(dim='lon').sortby('lat')

    fig, ax = plt.subplots(figsize=(5.5, 8))
    ax.axvline(0, color='black', lw=1, alpha=0.4)
    ax.plot(tuner_init, lat_tuner, label='Initial Bias (Base/Phis)', color='orange', linestyle='--', lw=1.8)
    ax.plot(tuner_pred, lat_tuner, label='Predicted Final (Emulator)', color='blue', linestyle=':', lw=2.2)
    ax.plot(model_zonal_realized, model_reg.lat.sortby('lat'), label=f'Realized Final ({exp_tag})', color='green', lw=2.5)
    
    ax.set_title(f'{var_tuner.upper()} Zonal Bias Validation\nRun: {exp_tag}', fontsize=12, fontweight='bold')
    ax.set_xlabel('Bias wrt CERES [W/m²]', fontsize=11)
    ax.set_ylabel('Latitude', fontsize=11)
    ax.grid(True, linestyle=':', alpha=0.5)
    ax.legend(loc='upper right', fontsize=9)
    ax.set_ylim(-90, 90)
    plt.tight_layout()
    _handle_show_or_save(output_path)


