files:
  reference: gm_reference_EC23.yml  # Reference file based on obs (our target)
  sensitivity: sensitivity_a000_{year1}-{year2}.yaml  # sensitivity file template
  base: global_mean_{exp}_EC-Earth4_r1i1p1f1_{year1}_{year2}.yml  # template for ecmean output filenames, name of the file to tune
  params: params_{exp}.yaml  # template for parameter files
  ecmean: ./ecmean  # directory for ecmean output files
  exps: ./exps  # directory for parameter files for each experiment
  exp_temp: s??? # template name for sensitivity runs (can include ?, *)
  slope_file: /ec/res4/hpcperm/ecme3038//ecearth/ecearth4/ECtuner/slopes.yaml # file with slopes for temperature correction

ecmean:
  ecmean_config: config_ecmean.yml

args:
  # Default years for sensitivities
  year1: 1990
  year2: 2000
  penalty: 10  # Penalty for deviation from reference parameter values
  inc: 0.2  # Maximum acceptable parameter change
  method: 'dual_annealing' # Optimization method (dual_annealing (recommended), differential_evolution, shgo (not 
  deltaT: 0.5 # Time step for the reference correction 

reference_parameters: # Default OIFS parameter values (used for penalty)
  RPRCON: 0.0014
  ENTRORG: 0.00175
  DETRPEN: 7.5e-05
  ENTRDD: 0.0003
  RMFDEPS: 0.3
  RVICE: 0.13
  RLCRITSNOW: 2.0e-05
  RSNOWLIN2: 0.03
  RCLDIFF: 6.0e-06
  RCLDIFF_CONVI: 10.0

parameter_group: # Parameter grouping for SE output
  namcumf: 
    - RPRCON
    - ENTRORG
    - DETRPEN
    - ENTRDD
    - RMFDEPS
  namcldp:
    - RVICE
    - RLCRITSNOW
    - RSNOWLIN2
    - RCLDIFF
    - RCLDIFF_CONVI
  
weights_season:  # Weights for different seasons
  ALL: 1.0
  DJF: 0.
  JJA: 0.

weights_region:  # Weights for different regions
  Global: 1.0
  North Midlat: 0.3
  South Midlat: 0.3
  Tropical: 0.3

weights:  # Weights for different target variables
  net_toa: 3.0
  rsnt: 0.5
  rlnt: 0.5
  swcf: 0.2
  lwcf: 0.2
  rsns: 0.
  rlns: 0.
  hfss: 0.
  hfls: 0.
  net_sfc: 0.
  toamsfc: 0.

  # rsnt: 0.5
  # rlnt: 0.5
  # swcf: 0.3
  # lwcf: 0.3
  # rsns: 0.1
  # rlns: 0.1
  # hfss: 0.1
  # hfls: 0.1
  # net_sfc: 0.3
  # toamsfc: 0.1